---
- hosts: all
  become: yes
  tasks:
    - name: Gather disk information
      command: lsblk -o NAME,MOUNTPOINT,LABEL
      register: disk_info
      changed_when: false


    - name: Label disks if necessary
      command: e2label {{ item.split()[0] }} {{ label_dict[item.split()[1]] }}
      with_items: "{{ disk_info.stdout_lines }}"
      when: "'LABEL' not in item and item.split()[1] in ['/var/lib/rancher', '/var/lib/log', '/var/lib/kubectl']"
      vars:
        label_dict:
          '/var/lib/rancher': 'CONTAINERS'
          '/var/lib/log': 'LOG'
          '/var/lib/kubectl': 'KUBELET'


    - name: Gather disk information again
      command: lsblk -o NAME,LABEL
      register: disk_info
      changed_when: false


    - name: Check if disks have labels
      assert:
        that: "item.split()[1] is defined"
        fail_msg: "One or more disks don't have labels, please make sure to label them first."
        success_msg: "All disks have labels. Continuing..."
      loop: "{{ disk_info.stdout_lines }}"
      loop_control:
        label: "{{ item.split()[0] }}"


    - name: Gather current fstab entries
      command: cat /etc/fstab
      register: fstab_info
      changed_when: false


    - name: Update fstab entries
      block:
        - name: Find fstab line for the disk
          set_fact:
            fstab_line: "{{ fstab_info.stdout_lines | select('match', '^'+item.split()[0]+'\s.*') | list | first }}"
          when: "fstab_info.stdout_lines | select('match', '^'+item.split()[0]+'\s.*') | list | length > 0"


        - name: Update the fstab entry
          lineinfile:
            path: /etc/fstab
            regexp: '^' + item.split()[0]
            line: 'LABEL={{ item.split()[1] }}\t{{ fstab_line.split()[1:] | join(' ') }}'
          when: "item.split()[0] in fstab_info.stdout and item.split()[1] in ['CONTAINERS', 'LOG', 'KUBELET'] and fstab_line is defined"
      loop: "{{ disk_info.stdout_lines }}"