---
- hosts: all
  become: yes
  tasks:
    - name: Gather disk information again
      shell: lsblk -nd -o NAME,LABEL |grep -v sda
      register: disk_info
      changed_when: false


    - name: Check if disks have labels
      assert:
        that: "item.split()[1] is defined"
        fail_msg: "One or more disks don't have labels, please make sure to label them first."
        success_msg: "All disks have labels. Continuing..."
      loop: "{{ disk_info.stdout_lines }}"
      loop_control:
        label: "{{ item.split()[0] }}"

 
    - name: e2label command 
      command: e2label {{ item.split()[0] }} {{ mount_point_dict[item.split()[0]] }}
      loop: "{{ disk_info.stdout_lines }}"
      when: "'LABEL' not in item and item.split()[1] in ['/var/lib/rancher', '/var/lib/logs', '/var/lib/kub
ectl']"
      register: e2label_result
      vars: 
         mount_point_dict:
                 '/var/lib/rancher': 'CONTAINERS'
                 '/var/lib/log': 'LOGS'
                 '/var/lib/kubectl': 'KUBELET'
      changed_when: false


    - name: Gather current fstab entries
      command: cat /etc/fstab
      register: fstab_info
      changed_when: false


    - name: Update fstab entries
      include_tasks: update_fstab.yaml
      loop: "{{ disk_info.stdout_lines }}"
